[2023-04-05T03:41:18.563+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT.transform manual__2023-04-05T03:41:16.228544+00:00 [queued]>
[2023-04-05T03:41:18.571+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT.transform manual__2023-04-05T03:41:16.228544+00:00 [queued]>
[2023-04-05T03:41:18.571+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T03:41:18.571+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-05T03:41:18.572+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T03:41:18.585+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): transform> on 2023-04-05 03:41:16.228544+00:00
[2023-04-05T03:41:18.591+0000] {standard_task_runner.py:55} INFO - Started process 1593 to run task
[2023-04-05T03:41:18.595+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ELT', 'transform', 'manual__2023-04-05T03:41:16.228544+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp4bucqj93']
[2023-04-05T03:41:18.595+0000] {standard_task_runner.py:83} INFO - Job 39: Subtask transform
[2023-04-05T03:41:18.645+0000] {task_command.py:389} INFO - Running <TaskInstance: ELT.transform manual__2023-04-05T03:41:16.228544+00:00 [running]> on host 385ee18f1e17
[2023-04-05T03:41:18.704+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=200300600@ucaribe.edu.mx
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T03:41:16.228544+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-05T03:41:16.228544+00:00
[2023-04-05T03:41:18.706+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-05T03:41:18.707+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'run --project-dir demo']
[2023-04-05T03:41:18.723+0000] {subprocess.py:86} INFO - Output:
[2023-04-05T03:41:18.726+0000] {subprocess.py:93} INFO - /bin/bash: line 1: run: command not found
[2023-04-05T03:41:18.726+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-04-05T03:41:18.735+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-04-05T03:41:18.739+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ELT, task_id=transform, execution_date=20230405T034116, start_date=20230405T034118, end_date=20230405T034118
[2023-04-05T03:41:18.749+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 39 for task transform (Bash command failed. The command returned a non-zero exit code 127.; 1593)
[2023-04-05T03:41:18.766+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T03:41:18.783+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
