[2023-04-05T04:39:08.255+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:39:06.179816+00:00 [queued]>
[2023-04-05T04:39:08.263+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:39:06.179816+00:00 [queued]>
[2023-04-05T04:39:08.263+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:39:08.263+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-05T04:39:08.263+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:39:08.275+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): object_transformation.sql> on 2023-04-05 04:39:06.179816+00:00
[2023-04-05T04:39:08.282+0000] {standard_task_runner.py:55} INFO - Started process 203 to run task
[2023-04-05T04:39:08.285+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ELT', 'object_transformation.sql', 'manual__2023-04-05T04:39:06.179816+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpe0da0x3o']
[2023-04-05T04:39:08.285+0000] {standard_task_runner.py:83} INFO - Job 79: Subtask object_transformation.sql
[2023-04-05T04:39:08.343+0000] {task_command.py:389} INFO - Running <TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:39:06.179816+00:00 [running]> on host f5e703d34d7f
[2023-04-05T04:39:08.405+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=200300600@ucaribe.edu.mx
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT
AIRFLOW_CTX_TASK_ID=object_transformation.sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T04:39:06.179816+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-05T04:39:06.179816+00:00
[2023-04-05T04:39:08.408+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-05T04:39:08.409+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --projects_dir /demo']
[2023-04-05T04:39:08.424+0000] {subprocess.py:86} INFO - Output:
[2023-04-05T04:39:10.454+0000] {subprocess.py:93} INFO - usage: dbt [-h] [--version] [-r RECORD_TIMING_INFO] [-d]
[2023-04-05T04:39:10.454+0000] {subprocess.py:93} INFO -            [--log-format {text,json,default}] [--no-write-json]
[2023-04-05T04:39:10.455+0000] {subprocess.py:93} INFO -            [--use-colors | --no-use-colors] [--printer-width PRINTER_WIDTH]
[2023-04-05T04:39:10.455+0000] {subprocess.py:93} INFO -            [--warn-error | --warn-error-options WARN_ERROR_OPTIONS]
[2023-04-05T04:39:10.455+0000] {subprocess.py:93} INFO -            [--no-version-check] [--partial-parse | --no-partial-parse]
[2023-04-05T04:39:10.455+0000] {subprocess.py:93} INFO -            [--use-experimental-parser] [--no-static-parser]
[2023-04-05T04:39:10.456+0000] {subprocess.py:93} INFO -            [--profiles-dir PROFILES_DIR] [--no-anonymous-usage-stats] [-x]
[2023-04-05T04:39:10.456+0000] {subprocess.py:93} INFO -            [-q] [--no-print]
[2023-04-05T04:39:10.456+0000] {subprocess.py:93} INFO -            [--cache-selected-only | --no-cache-selected-only]
[2023-04-05T04:39:10.456+0000] {subprocess.py:93} INFO -            {docs,source,init,clean,debug,deps,list,ls,build,snapshot,run,compile,parse,test,seed,run-operation}
[2023-04-05T04:39:10.457+0000] {subprocess.py:93} INFO -            ...
[2023-04-05T04:39:10.457+0000] {subprocess.py:93} INFO - dbt: error: unrecognized arguments: --projects_dir /demo
[2023-04-05T04:39:10.651+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-05T04:39:10.662+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-05T04:39:10.666+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ELT, task_id=object_transformation.sql, execution_date=20230405T043906, start_date=20230405T043908, end_date=20230405T043910
[2023-04-05T04:39:10.687+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 79 for task object_transformation.sql (Bash command failed. The command returned a non-zero exit code 2.; 203)
[2023-04-05T04:39:10.703+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T04:39:10.720+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
