[2023-04-05T04:27:19.843+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:27:17.711063+00:00 [queued]>
[2023-04-05T04:27:19.852+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:27:17.711063+00:00 [queued]>
[2023-04-05T04:27:19.852+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:27:19.852+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-05T04:27:19.853+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:27:19.866+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): object_transformation.sql> on 2023-04-05 04:27:17.711063+00:00
[2023-04-05T04:27:19.872+0000] {standard_task_runner.py:55} INFO - Started process 487 to run task
[2023-04-05T04:27:19.875+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ELT', 'object_transformation.sql', 'manual__2023-04-05T04:27:17.711063+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpzh4_xd_l']
[2023-04-05T04:27:19.875+0000] {standard_task_runner.py:83} INFO - Job 61: Subtask object_transformation.sql
[2023-04-05T04:27:19.933+0000] {task_command.py:389} INFO - Running <TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:27:17.711063+00:00 [running]> on host 08fcf180c6cc
[2023-04-05T04:27:19.994+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=200300600@ucaribe.edu.mx
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT
AIRFLOW_CTX_TASK_ID=object_transformation.sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T04:27:17.711063+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-05T04:27:17.711063+00:00
[2023-04-05T04:27:19.998+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-05T04:27:19.998+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project_dir ~ /demo/models/object_transformation.sql']
[2023-04-05T04:27:20.012+0000] {subprocess.py:86} INFO - Output:
[2023-04-05T04:27:22.197+0000] {subprocess.py:93} INFO - usage: dbt [-h] [--version] [-r RECORD_TIMING_INFO] [-d]
[2023-04-05T04:27:22.197+0000] {subprocess.py:93} INFO -            [--log-format {text,json,default}] [--no-write-json]
[2023-04-05T04:27:22.198+0000] {subprocess.py:93} INFO -            [--use-colors | --no-use-colors] [--printer-width PRINTER_WIDTH]
[2023-04-05T04:27:22.198+0000] {subprocess.py:93} INFO -            [--warn-error | --warn-error-options WARN_ERROR_OPTIONS]
[2023-04-05T04:27:22.198+0000] {subprocess.py:93} INFO -            [--no-version-check] [--partial-parse | --no-partial-parse]
[2023-04-05T04:27:22.198+0000] {subprocess.py:93} INFO -            [--use-experimental-parser] [--no-static-parser]
[2023-04-05T04:27:22.198+0000] {subprocess.py:93} INFO -            [--profiles-dir PROFILES_DIR] [--no-anonymous-usage-stats] [-x]
[2023-04-05T04:27:22.199+0000] {subprocess.py:93} INFO -            [-q] [--no-print]
[2023-04-05T04:27:22.199+0000] {subprocess.py:93} INFO -            [--cache-selected-only | --no-cache-selected-only]
[2023-04-05T04:27:22.199+0000] {subprocess.py:93} INFO -            {docs,source,init,clean,debug,deps,list,ls,build,snapshot,run,compile,parse,test,seed,run-operation}
[2023-04-05T04:27:22.199+0000] {subprocess.py:93} INFO -            ...
[2023-04-05T04:27:22.199+0000] {subprocess.py:93} INFO - dbt: error: unrecognized arguments: --project_dir /home/*** /demo/models/object_transformation.sql
[2023-04-05T04:27:22.424+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-05T04:27:22.436+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-05T04:27:22.440+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ELT, task_id=object_transformation.sql, execution_date=20230405T042717, start_date=20230405T042719, end_date=20230405T042722
[2023-04-05T04:27:22.450+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 61 for task object_transformation.sql (Bash command failed. The command returned a non-zero exit code 2.; 487)
[2023-04-05T04:27:22.494+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T04:27:22.512+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
