[2023-04-05T03:39:52.795+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT.transform manual__2023-04-05T03:39:50.591897+00:00 [queued]>
[2023-04-05T03:39:52.803+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT.transform manual__2023-04-05T03:39:50.591897+00:00 [queued]>
[2023-04-05T03:39:52.803+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T03:39:52.803+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-05T03:39:52.803+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T03:39:52.817+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): transform> on 2023-04-05 03:39:50.591897+00:00
[2023-04-05T03:39:52.825+0000] {standard_task_runner.py:55} INFO - Started process 1543 to run task
[2023-04-05T03:39:52.829+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ELT', 'transform', 'manual__2023-04-05T03:39:50.591897+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp_pvtdn5g']
[2023-04-05T03:39:52.829+0000] {standard_task_runner.py:83} INFO - Job 37: Subtask transform
[2023-04-05T03:39:52.879+0000] {task_command.py:389} INFO - Running <TaskInstance: ELT.transform manual__2023-04-05T03:39:50.591897+00:00 [running]> on host 385ee18f1e17
[2023-04-05T03:39:52.935+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=200300600@ucaribe.edu.mx
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T03:39:50.591897+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-05T03:39:50.591897+00:00
[2023-04-05T03:39:52.940+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-05T03:39:52.941+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project-dir demo']
[2023-04-05T03:39:52.956+0000] {subprocess.py:86} INFO - Output:
[2023-04-05T03:39:52.960+0000] {subprocess.py:93} INFO - /bin/bash: line 1: dbt: command not found
[2023-04-05T03:39:52.961+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-04-05T03:39:52.970+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-04-05T03:39:52.973+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ELT, task_id=transform, execution_date=20230405T033950, start_date=20230405T033952, end_date=20230405T033952
[2023-04-05T03:39:52.986+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 37 for task transform (Bash command failed. The command returned a non-zero exit code 127.; 1543)
[2023-04-05T03:39:53.001+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T03:39:53.016+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
