[2023-04-05T04:28:12.883+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:28:10.301148+00:00 [queued]>
[2023-04-05T04:28:12.893+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:28:10.301148+00:00 [queued]>
[2023-04-05T04:28:12.893+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:28:12.893+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-05T04:28:12.893+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-05T04:28:12.904+0000] {taskinstance.py:1309} INFO - Executing <Task(BashOperator): object_transformation.sql> on 2023-04-05 04:28:10.301148+00:00
[2023-04-05T04:28:12.910+0000] {standard_task_runner.py:55} INFO - Started process 519 to run task
[2023-04-05T04:28:12.913+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ELT', 'object_transformation.sql', 'manual__2023-04-05T04:28:10.301148+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmps1cafopo']
[2023-04-05T04:28:12.913+0000] {standard_task_runner.py:83} INFO - Job 65: Subtask object_transformation.sql
[2023-04-05T04:28:12.969+0000] {task_command.py:389} INFO - Running <TaskInstance: ELT.object_transformation.sql manual__2023-04-05T04:28:10.301148+00:00 [running]> on host 08fcf180c6cc
[2023-04-05T04:28:13.034+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=200300600@ucaribe.edu.mx
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT
AIRFLOW_CTX_TASK_ID=object_transformation.sql
AIRFLOW_CTX_EXECUTION_DATE=2023-04-05T04:28:10.301148+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-05T04:28:10.301148+00:00
[2023-04-05T04:28:13.036+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-04-05T04:28:13.037+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --project_dir ~./demo']
[2023-04-05T04:28:13.055+0000] {subprocess.py:86} INFO - Output:
[2023-04-05T04:28:15.278+0000] {subprocess.py:93} INFO - usage: dbt [-h] [--version] [-r RECORD_TIMING_INFO] [-d]
[2023-04-05T04:28:15.278+0000] {subprocess.py:93} INFO -            [--log-format {text,json,default}] [--no-write-json]
[2023-04-05T04:28:15.278+0000] {subprocess.py:93} INFO -            [--use-colors | --no-use-colors] [--printer-width PRINTER_WIDTH]
[2023-04-05T04:28:15.278+0000] {subprocess.py:93} INFO -            [--warn-error | --warn-error-options WARN_ERROR_OPTIONS]
[2023-04-05T04:28:15.279+0000] {subprocess.py:93} INFO -            [--no-version-check] [--partial-parse | --no-partial-parse]
[2023-04-05T04:28:15.279+0000] {subprocess.py:93} INFO -            [--use-experimental-parser] [--no-static-parser]
[2023-04-05T04:28:15.279+0000] {subprocess.py:93} INFO -            [--profiles-dir PROFILES_DIR] [--no-anonymous-usage-stats] [-x]
[2023-04-05T04:28:15.279+0000] {subprocess.py:93} INFO -            [-q] [--no-print]
[2023-04-05T04:28:15.280+0000] {subprocess.py:93} INFO -            [--cache-selected-only | --no-cache-selected-only]
[2023-04-05T04:28:15.280+0000] {subprocess.py:93} INFO -            {docs,source,init,clean,debug,deps,list,ls,build,snapshot,run,compile,parse,test,seed,run-operation}
[2023-04-05T04:28:15.280+0000] {subprocess.py:93} INFO -            ...
[2023-04-05T04:28:15.280+0000] {subprocess.py:93} INFO - dbt: error: unrecognized arguments: --project_dir ~./demo
[2023-04-05T04:28:15.552+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-04-05T04:28:15.571+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-04-05T04:28:15.575+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=ELT, task_id=object_transformation.sql, execution_date=20230405T042810, start_date=20230405T042812, end_date=20230405T042815
[2023-04-05T04:28:15.589+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 65 for task object_transformation.sql (Bash command failed. The command returned a non-zero exit code 2.; 519)
[2023-04-05T04:28:15.612+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-05T04:28:15.646+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
